version: '2'

services:

   transmission:
     image: carlosedp/transmission
     restart: unless-stopped
     ports:
       - "9091:9091"
       - "51413:51413"
       - "51413:51413/udp"
     volumes:
       - transmission_config:/etc/transmission-daemon
       - /etc/localtime:/etc/localtime:ro
       - ${MEDIA}/Downloads:/downloads
       - ${MEDIA}/Downloads/Incomplete:/volumes/media/Downloads/Incomplete
     labels:
       - "traefik.backend=transmission"
       - "traefik.frontend.rule=Host:transmission.cloud.carlosedp.com"
       - "traefik.enable=true"
       - "traefik.port=9091"
       - "traefik.docker.network=containermgmt_traefik"
       - "traefik.default.protocol=http"

   sickrage:
     depends_on:
       - transmission
     image: sickrage/sickrage:arm64v8-latest
     restart: unless-stopped
     ports:
       - "8081:8081"
     volumes:
       - sickrage_config:/config
       - ${MEDIA}/Downloads:/downloads
       - ${MEDIA}/TVShows:/tv
       - /etc/localtime:/etc/localtime:ro
     environment:
       PGID: ${GROUP_ID}
       PUID: ${USER_ID}
     labels:
       - "traefik.backend=sickrage"
       - "traefik.frontend.rule=Host:sickrage.cloud.carlosedp.com"
       - "traefik.enable=true"
       - "traefik.port=8081"
       - "traefik.docker.network=containermgmt_traefik"
       - "traefik.default.protocol=http"

   couchpotato:
     depends_on:
       - transmission
     image: carlosedp/couchpotato
     restart: unless-stopped
     ports:
       - "5050:5050"
     volumes:
       - ${MEDIA}/Downloads:/downloads
       - ${MEDIA}:/volumes/media
       - couchpotato_data:/volumes/data
       - couchpotato_config:/volumes/config
       - /etc/localtime:/etc/localtime:ro
     labels:
       - "traefik.backend=couchpotato"
       - "traefik.frontend.rule=Host:couchpotato.cloud.carlosedp.com"
       - "traefik.enable=true"
       - "traefik.port=5050"
       - "traefik.docker.network=containermgmt_traefik"
       - "traefik.default.protocol=http"

   plex:
     image: jaymoulin/plex
     restart: unless-stopped
     network_mode: "host"
     ports:
       - 32400:32400/tcp
       - 3005:3005/tcp
       - 8324:8324/tcp
       - 32469:32469/tcp
       - 1900:1900/udp
       - 32410:32410/udp
       - 32412:32412/udp
       - 32413:32413/udp
       - 32414:32414/udp
     volumes:
       - ${MEDIA}:/media
       - plex_config:/root/Library
       - /etc/localtime:/etc/localtime:ro
     labels:
       - "traefik.backend=plex"
       - "traefik.frontend.rule=Host:plex.cloud.carlosedp.com"
       - "traefik.enable=true"
       - "traefik.port=32400"
       - "traefik.docker.network=containermgmt_traefik"
       - "traefik.default.protocol=http"

   vnstatd:
     image: carlosedp/vnstatd
     network_mode: "host"
     restart: unless-stopped
     privileged: true
     volumes:
       - vnstat_data:/var/lib/vnstat
       - /etc/localtime:/etc/localtime:ro

   htpcmanager:
     depends_on:
       - vnstatd
     image: carlosedp/htpcmanager
     restart: unless-stopped
     ports:
       - "8085:8085"
     volumes:
       - htpcmanager_config:/config
       - vnstat_data:/var/lib/vnstat
       - /mnt:/mnt
       - /etc/localtime:/etc/localtime:ro
     environment:
       PGID: ${GROUP_ID}
       PUID: ${USER_ID}
     networks:
       - default
       - traefik
     labels:
       - "traefik.backend=htpcmanager"
       - "traefik.frontend.rule=Host:htpcmanager.cloud.carlosedp.com"
       - "traefik.enable=true"
       - "traefik.port=8085"
       - "traefik.docker.network=containermgmt_traefik"
       - "traefik.default.protocol=http"

volumes:
    transmission_config:
    sickrage_config:
    couchpotato_data:
    couchpotato_config:
    plex_config:
    vnstat_data:
    htpcmanager_config:

networks:
    default:
    traefik:
      external:
        name: containermgmt_traefik
